import User from './models/User.js';
import Product from './models/Product.js';

const products = [
  { name: 'Premium Cotton T-Shirt', slug: 'premium-cotton-tshirt', description: 'Soft, breathable cotton t-shirt perfect for everyday wear. Classic fit with reinforced stitching.', price: 899, salePrice: 699, category: 'Clothing', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600', stock: 50, rating: 4.5, numReviews: 24, featured: true, sizes: ['S', 'M', 'L', 'XL'], colors: ['White', 'Black', 'Navy'] },
  { name: 'Classic Denim Jacket', slug: 'classic-denim-jacket', description: 'Timeless denim jacket with modern cut. Durable and stylish for all seasons.', price: 2499, category: 'Clothing', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600', stock: 30, rating: 4.7, numReviews: 18, featured: true, sizes: ['S', 'M', 'L', 'XL'], colors: ['Blue', 'Black'] },
  { name: 'Running Sneakers Pro', slug: 'running-sneakers-pro', description: 'Lightweight running shoes with cushioned sole and breathable mesh upper.', price: 3999, salePrice: 3299, category: 'Footwear', brand: 'MERN Sport', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600', stock: 40, rating: 4.8, numReviews: 56, featured: true, sizes: ['7', '8', '9', '10', '11'], colors: ['Red', 'Black', 'White'] },
  { name: 'Leather Crossbody Bag', slug: 'leather-crossbody-bag', description: 'Genuine leather crossbody bag with adjustable strap and multiple compartments.', price: 1899, category: 'Accessories', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600', stock: 25, rating: 4.4, numReviews: 12, featured: true, colors: ['Brown', 'Black'] },
  { name: 'Wireless Bluetooth Earbuds', slug: 'wireless-bluetooth-earbuds', description: 'Premium sound quality with active noise cancellation and 24-hour battery life.', price: 2999, salePrice: 2499, category: 'Electronics', brand: 'MERN Tech', image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600', stock: 60, rating: 4.6, numReviews: 89, featured: true, colors: ['White', 'Black'] },
  { name: 'Smart Fitness Watch', slug: 'smart-fitness-watch', description: 'Track your health metrics, workouts, and sleep with this advanced smartwatch.', price: 4999, category: 'Electronics', brand: 'MERN Tech', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600', stock: 35, rating: 4.9, numReviews: 42, featured: true, colors: ['Black', 'Silver'] },
  { name: 'Slim Fit Chinos', slug: 'slim-fit-chinos', description: 'Comfortable stretch chinos with a modern slim fit.', price: 1599, category: 'Clothing', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600', stock: 45, rating: 4.3, numReviews: 15, sizes: ['30', '32', '34', '36'], colors: ['Khaki', 'Navy', 'Grey'] },
  { name: 'Polarized Sunglasses', slug: 'polarized-sunglasses', description: 'UV400 protection with polarized lenses.', price: 1299, salePrice: 999, category: 'Accessories', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1572635196233-224f5e298d8a?w=600', stock: 55, rating: 4.5, numReviews: 31, colors: ['Black', 'Tortoise'] },
  { name: 'Wool Blend Sweater', slug: 'wool-blend-sweater', description: 'Cozy wool blend sweater with ribbed cuffs.', price: 2199, category: 'Clothing', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600', stock: 28, rating: 4.6, numReviews: 22, sizes: ['S', 'M', 'L', 'XL'], colors: ['Grey', 'Navy', 'Burgundy'] },
  { name: 'Canvas Sneakers', slug: 'canvas-sneakers', description: 'Classic canvas sneakers with rubber sole.', price: 1499, category: 'Footwear', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8d857?w=600', stock: 70, rating: 4.2, numReviews: 38, sizes: ['7', '8', '9', '10', '11'], colors: ['White', 'Navy', 'Red'] },
  { name: 'Stainless Steel Water Bottle', slug: 'stainless-steel-water-bottle', description: 'Insulated 750ml bottle keeps drinks cold for 24 hours.', price: 799, category: 'Accessories', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600', stock: 100, rating: 4.7, numReviews: 67, colors: ['Silver', 'Black', 'Blue'] },
  { name: 'Portable Bluetooth Speaker', slug: 'portable-bluetooth-speaker', description: 'Waterproof portable speaker with 360° sound.', price: 3499, salePrice: 2799, category: 'Electronics', brand: 'MERN Tech', image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600', stock: 42, rating: 4.5, numReviews: 45, colors: ['Black', 'Blue'] },
  // 20 NEW PRODUCTS
  { name: 'iPhone 15 Pro Max Case', slug: 'iphone-15-pro-max-case', description: 'Premium silicone case with MagSafe compatibility and drop protection.', price: 1299, salePrice: 999, category: 'Electronics', brand: 'MERN Tech', image: 'https://images.unsplash.com/photo-1601784551445-20c9e07cdbdb?w=600', stock: 80, rating: 4.6, numReviews: 34, featured: true, colors: ['Black', 'Blue', 'Clear'] },
  { name: 'Gaming Mechanical Keyboard', slug: 'gaming-mechanical-keyboard', description: 'RGB backlit mechanical keyboard with blue switches for gaming enthusiasts.', price: 4499, salePrice: 3799, category: 'Electronics', brand: 'MERN Tech', image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600', stock: 25, rating: 4.8, numReviews: 67, featured: true, colors: ['Black'] },
  { name: '4K Ultra HD Smart TV 43"', slug: '4k-smart-tv-43', description: 'Crystal clear 4K display with built-in streaming apps and voice control.', price: 28999, salePrice: 24999, category: 'Electronics', brand: 'MERN Tech', image: 'https://images.unsplash.com/photo-1593359673509-f6a4b7d9bf1e?w=600', stock: 15, rating: 4.7, numReviews: 28, featured: true },
  { name: 'Wireless Charging Pad', slug: 'wireless-charging-pad', description: 'Fast 15W wireless charger compatible with all Qi-enabled devices.', price: 1499, category: 'Electronics', brand: 'MERN Tech', image: 'https://images.unsplash.com/photo-1591290619762-d2f5c3d9f1e4?w=600', stock: 90, rating: 4.4, numReviews: 52, colors: ['White', 'Black'] },
  { name: 'Laptop Stand Aluminum', slug: 'laptop-stand-aluminum', description: 'Ergonomic aluminum laptop stand with adjustable height and cooling design.', price: 2199, category: 'Electronics', brand: 'MERN Tech', image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600', stock: 40, rating: 4.5, numReviews: 19, colors: ['Silver', 'Space Grey'] },
  { name: 'USB-C Hub 7-in-1', slug: 'usb-c-hub-7in1', description: 'Multi-port USB-C hub with HDMI, USB 3.0, SD card reader and PD charging.', price: 2799, salePrice: 2299, category: 'Electronics', brand: 'MERN Tech', image: 'https://images.unsplash.com/photo-1625948515291-69613efd707c?w=600', stock: 55, rating: 4.6, numReviews: 41, colors: ['Grey'] },
  { name: 'Over-Ear Headphones', slug: 'over-ear-headphones', description: 'Studio-quality over-ear headphones with 40mm drivers and plush ear cushions.', price: 5999, salePrice: 4999, category: 'Electronics', brand: 'MERN Tech', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600', stock: 30, rating: 4.9, numReviews: 78, featured: true, colors: ['Black', 'White'] },
  { name: 'Tablet 10" Android', slug: 'tablet-10-android', description: '10-inch HD tablet with 64GB storage, dual cameras and long battery life.', price: 12999, salePrice: 10999, category: 'Electronics', brand: 'MERN Tech', image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600', stock: 20, rating: 4.5, numReviews: 33, colors: ['Silver', 'Black'] },
  { name: 'Formal White Shirt', slug: 'formal-white-shirt', description: 'Crisp cotton formal shirt perfect for office and special occasions.', price: 1799, salePrice: 1399, category: 'Clothing', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1596755094514-f87e3408b558?w=600', stock: 60, rating: 4.4, numReviews: 27, sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['White', 'Light Blue'] },
  { name: 'Floral Summer Dress', slug: 'floral-summer-dress', description: 'Elegant floral print midi dress with flowing silhouette for summer occasions.', price: 2299, category: 'Clothing', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92d1?w=600', stock: 35, rating: 4.7, numReviews: 44, featured: true, sizes: ['S', 'M', 'L'], colors: ['Floral Pink', 'Floral Blue'] },
  { name: 'Men\'s Leather Belt', slug: 'mens-leather-belt', description: 'Genuine leather belt with classic buckle, fits all standard trouser loops.', price: 999, category: 'Clothing', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=600', stock: 75, rating: 4.3, numReviews: 18, sizes: ['32', '34', '36', '38'], colors: ['Brown', 'Black'] },
  { name: 'Hooded Sweatshirt', slug: 'hooded-sweatshirt', description: 'Premium fleece-lined hoodie with kangaroo pocket and drawstring hood.', price: 1899, salePrice: 1499, category: 'Clothing', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600', stock: 50, rating: 4.6, numReviews: 62, sizes: ['S', 'M', 'L', 'XL'], colors: ['Grey', 'Black', 'Navy'] },
  { name: 'Women\'s Palazzo Pants', slug: 'womens-palazzo-pants', description: 'Flowy wide-leg palazzo pants in breathable cotton blend fabric.', price: 1399, category: 'Clothing', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600', stock: 40, rating: 4.5, numReviews: 29, sizes: ['S', 'M', 'L', 'XL'], colors: ['Black', 'Olive', 'Maroon'] },
  { name: 'Checked Casual Shirt', slug: 'checked-casual-shirt', description: 'Trendy checked pattern casual shirt for a smart-casual look.', price: 1299, category: 'Clothing', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1598033129185-c4f8c735fbf8?w=600', stock: 55, rating: 4.4, numReviews: 21, sizes: ['S', 'M', 'L', 'XL'], colors: ['Red Check', 'Blue Check'] },
  { name: 'Sports Track Pants', slug: 'sports-track-pants', description: 'Lightweight moisture-wicking track pants for gym and outdoor activities.', price: 1199, salePrice: 899, category: 'Clothing', brand: 'MERN Sport', image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600', stock: 65, rating: 4.3, numReviews: 37, sizes: ['S', 'M', 'L', 'XL'], colors: ['Black', 'Navy', 'Grey'] },
  { name: 'Silk Saree Premium', slug: 'silk-saree-premium', description: 'Handwoven pure silk saree with intricate border design for festive occasions.', price: 4999, salePrice: 3999, category: 'Clothing', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600', stock: 18, rating: 4.9, numReviews: 15, featured: true, colors: ['Red', 'Green', 'Gold'] },
  { name: 'Leather Formal Shoes', slug: 'leather-formal-shoes', description: 'Handcrafted genuine leather oxford shoes for formal and business wear.', price: 3499, salePrice: 2999, category: 'Footwear', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1614252238946-8023a4ed3e1e?w=600', stock: 30, rating: 4.7, numReviews: 48, sizes: ['7', '8', '9', '10', '11'], colors: ['Brown', 'Black'] },
  { name: 'Women\'s Heels Stiletto', slug: 'womens-heels-stiletto', description: 'Elegant stiletto heels with cushioned insole for all-day comfort.', price: 2799, category: 'Footwear', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600', stock: 25, rating: 4.5, numReviews: 36, sizes: ['5', '6', '7', '8'], colors: ['Black', 'Nude', 'Red'] },
  { name: 'Smart LED Desk Lamp', slug: 'smart-led-desk-lamp', description: 'Adjustable LED desk lamp with touch control, USB charging port and eye-care mode.', price: 1899, category: 'Electronics', brand: 'MERN Tech', image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600', stock: 45, rating: 4.4, numReviews: 23, colors: ['White', 'Black'] },
  { name: 'Power Bank 20000mAh', slug: 'power-bank-20000mah', description: 'High-capacity 20000mAh power bank with fast charging and dual USB ports.', price: 1999, salePrice: 1599, category: 'Electronics', brand: 'MERN Tech', image: 'https://images.unsplash.com/photo-1620578024438-0ecb894ca973?w=600', stock: 70, rating: 4.6, numReviews: 91, featured: true, colors: ['Black', 'Blue'] },
  { name: 'Cotton Kurta Set', slug: 'cotton-kurta-set', description: 'Traditional cotton kurta with matching pajama, perfect for festivals and casual wear.', price: 1699, category: 'Clothing', brand: 'MERN Stack', image: 'https://images.unsplash.com/photo-1583292650898-7d22cd27dd6f?w=600', stock: 42, rating: 4.6, numReviews: 53, sizes: ['S', 'M', 'L', 'XL'], colors: ['White', 'Blue', 'Cream'] },
];

const EXPECTED_PRODUCT_COUNT = 32;

export const seedDatabase = async () => {
  const productCount = await Product.countDocuments();

  if (productCount < EXPECTED_PRODUCT_COUNT) {
    await Product.deleteMany();
    await Product.insertMany(products);
    console.log(`Seeded ${products.length} products`);
  }

  const userCount = await User.countDocuments();
  if (userCount === 0) {
    await User.create({ name: 'Admin User', email: 'admin@ecommerce.com', password: 'admin123', role: 'admin' });
    await User.create({ name: 'Demo User', email: 'user@ecommerce.com', password: 'user123', role: 'user' });
    console.log('Demo users created');
    console.log('Admin: admin@ecommerce.com / admin123');
    console.log('User:  user@ecommerce.com / user123');
  }
};
